{
 "title": "Satisfaction client",
 "time": { "from": "now", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": " quantité d'espace disque utilisé de la VM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!=\"tmpfs\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Date dernier appel de l'application",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_last_time_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de requête dans chaque bucket de l'application",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (round(increase(fastapi_latency_histogram_seconds_bucket[5m])))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pourcentage de RAM utilisée de la VM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de requête en cours de chargement de l'application",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fastapiinprogress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latence moyenne sur les 5 dernières minutes de l'application",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(fastapi_latency_summary_seconds_sum[5m])) / sum(rate(fastapi_latency_summary_seconds_count[5m]))\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}