# Dockerfile for PostgreSQL service
FROM python:3.9-slim

WORKDIR /app

COPY ./psgr/Postgresql_vf.py /app/psgr/Postgresql_vf.py

COPY ./psgr/requirements.txt /app/

# Installer les outils de développement PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev

RUN pip install -r requirements.txt

CMD ["python", "psgr/Postgresql_vf.py"]
