# Dockerfile for MongoDB service
FROM python:3.9-slim

WORKDIR /app

COPY ./mongodb/Mongo_vf.py /app/
COPY ../psgr/Postgresql_vf.py /app/
COPY ./mongodb/requirements.txt /app/

RUN pip install -r requirements.txt

CMD ["python", "./mongodb/Mongo_vf.py"]
