# Utiliser l'image Python basée sur Alpine
FROM python:3.9-alpine

#WORKDIR /

# COpy requirements sur conteneur
COPY crawl/crawl_src/requirements.txt . 
# copie des sources du code
COPY crawl/crawl_src/ .

# install dependances sur le conteneur
RUN pip install -r requirements.txt

# Forcer la creation des dossiers  des fichiers vides pour les dossiers temporaires et d'output
RUN mkdir temp
RUN mkdir out

# Rend les entrypoint executables
RUN chmod +x exe_update_firmInfos.py
RUN chmod +x exe_update_review.py

ENTRYPOINT ["python", "main.py"]